import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import AppHeader from "@/components/header";
import { MantineProvider } from "@mantine/core"
const inter = Inter({ subsets: ["latin"] });
import '@mantine/core/styles.css';
import '@mantine/dates/styles.css'; //if using mantine date picker features
import 'mantine-react-table/styles.css';
import { QueryProvider } from "@/providers/query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

      <html lang="en">
        <body className={inter.className}>
          <main>
            <QueryProvider>
              <MantineProvider>
                {children}
              </MantineProvider>
            </QueryProvider>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
